name: covid-reporting-adf-anup

on:
  push:
    branches:
      - main

jobs:
  deploy-adf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ADF resources
      uses: Azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: 'covid-reporting-rg'
        template: './arm-template/ARMTemplateForFactory.json'
        parameters: './arm-template/ARMTemplateParametersForFactory.json'
        deploymentName: 'adf-deployment'
        
    - name: Upload ARM Template Artifact
      uses: actions/upload-artifact@v3
      with:
         name: arm-template
         path: './arm-template/ARMTemplateForFactory.json'
